// Builds the printable doctor-summary page and drives the browser's print
// dialog (where the user picks "Save as PDF").

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// Minimal markdown → HTML for the fixed structure the summary uses
// (## headings, "- " bullets, **bold**). Input is escaped first.
function mdToHtml(md: string): string {
  const lines = escapeHtml(md).split("\n");
  const out: string[] = [];
  let inList = false;

  const closeList = () => {
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
  };

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      closeList();
      continue;
    }
    const bolded = line.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    if (line.startsWith("### ")) {
      closeList();
      out.push(`<h3>${bolded.slice(4)}</h3>`);
    } else if (line.startsWith("## ")) {
      closeList();
      out.push(`<h2>${bolded.slice(3)}</h2>`);
    } else if (line.startsWith("- ")) {
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${bolded.slice(2)}</li>`);
    } else {
      closeList();
      out.push(`<p>${bolded}</p>`);
    }
  }
  closeList();
  return out.join("\n");
}

const MARK_SVG = `<svg viewBox="6 28 108 82" width="34" height="26" xmlns="http://www.w3.org/2000/svg"><g stroke="#1F5C45" stroke-width="3" stroke-linecap="round" fill="none" opacity="0.9"><path d="M60 95 C 53 100, 47 102, 41 106"/><path d="M60 95 C 60 101, 60 104, 60 108"/><path d="M60 95 C 67 100, 73 102, 79 106"/></g><path d="M60 96 C 57 82, 63 68, 60 52" stroke="#1F5C45" stroke-width="4.4" fill="none" stroke-linecap="round"/><g fill="#D98E5A"><circle cx="58.3" cy="84" r="2.5"/><circle cx="61.2" cy="74" r="2.5"/><circle cx="59.2" cy="63.5" r="2.5"/></g><path d="M60 55 C 49 53, 39 48, 33 39 C 42 39, 53 44, 60 55 Z" fill="#74B58C"/><path d="M60 48 C 70 45, 80 40, 85 31 C 75 32, 64 38, 60 48 Z" fill="#4E9E72"/></svg>`;

export function buildPrintHtml(summaryMarkdown: string): string {
  const date = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // The document's own "# " title line becomes the page heading.
  let title = "Summary";
  let body = summaryMarkdown;
  const titleMatch = summaryMarkdown.match(/^\s*#\s+(.+)\s*$/m);
  if (titleMatch) {
    title = titleMatch[1].replace(/\*\*/g, "").trim();
    body = summaryMarkdown.replace(titleMatch[0], "").trim();
  }

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Helagi — Summary for your doctor</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: Georgia, "Times New Roman", serif;
    color: #23332b;
    max-width: 720px;
    margin: 0 auto;
    padding: 40px 32px;
    line-height: 1.5;
  }
  header {
    display: flex; align-items: center; justify-content: space-between;
    border-bottom: 2px solid #1F5C45; padding-bottom: 14px; margin-bottom: 8px;
  }
  .brand { display: flex; align-items: flex-end; gap: 8px; }
  .brand span { font-size: 26px; color: #1F5C45; line-height: 0.85; }
  .date { font-size: 13px; color: #6b7a70; }
  h1 { font-size: 20px; font-weight: 500; color: #143B2C; margin: 18px 0 4px; }
  .note {
    font-size: 12.5px; color: #6b7a70; font-style: italic;
    margin-bottom: 18px;
  }
  h2 {
    font-size: 15px; color: #143B2C; margin: 18px 0 6px;
    border-bottom: 1px solid rgba(31,92,69,.2); padding-bottom: 3px;
  }
  h3 { font-size: 14px; color: #143B2C; margin: 12px 0 4px; }
  ul { padding-left: 20px; margin-bottom: 6px; }
  li { margin-bottom: 3px; font-size: 14px; }
  p { font-size: 14px; margin-bottom: 6px; }
  footer {
    margin-top: 28px; padding-top: 12px; border-top: 1px solid rgba(31,92,69,.2);
    font-size: 11.5px; color: #6b7a70;
  }
  @media print {
    body { padding: 0; }
  }
</style>
</head>
<body>
  <header>
    <div class="brand">${MARK_SVG}<span>helagi</span></div>
    <div class="date">${date}</div>
  </header>
  <h1>${escapeHtml(title)}</h1>
  <p class="note">Prepared from a conversation with the Helagi medical assistant. AI-generated — for information and discussion, not a diagnosis or a substitute for professional advice.</p>
  ${mdToHtml(body)}
  <footer>Generated by Helagi (helagi medical AI assistant) on ${date}. This document reflects only what the user reported in the chat and the AI's non-diagnostic suggestions. Professional judgement always takes precedence.</footer>
  <script>window.onload = function () { setTimeout(function () { window.print(); }, 250); };</script>
</body>
</html>`;
}
