// PLACEHOLDER legal text — must be reviewed by a lawyer before public launch.
// This expands the short in-app disclaimer; the substance must stay aligned
// with the system prompt's safety rules (lib/systemPrompt.ts).

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Medical Disclaimer — Helagi",
};

export default function MedicalDisclaimerPage() {
  return (
    <>
      <h1>Medical Disclaimer</h1>
      <p className="updated">Draft — requires legal review before launch.</p>

      <h2>Helagi is not a doctor</h2>
      <p>
        Helagi provides general health information generated by an AI system,
        grounded where possible in the World Health Organization&rsquo;s ICD-11
        classification. Its answers are <strong>informational only</strong>:
        they are not a medical diagnosis, not medical advice, and not a
        treatment recommendation. Helagi does not replace a doctor, nurse,
        pharmacist, emergency service, or any other qualified healthcare
        professional.
      </p>

      <h2>In an emergency</h2>
      <p>
        If you have severe chest pain, trouble breathing, heavy bleeding,
        stroke symptoms, thoughts of harming yourself, or any other emergency:
        <strong> call your local emergency number (like 112 or 911) immediately</strong>.
        Do not wait for a chat response.
      </p>

      <h2>Limits you should know about</h2>
      <ul>
        <li>
          AI systems can be wrong, incomplete, or out of date — even when they
          sound confident.
        </li>
        <li>
          Helagi describes the <em>most likely</em> explanation, not a
          certainty. Only a clinician who examines you can diagnose you.
        </li>
        <li>
          Never start, stop, or change medication based on Helagi&rsquo;s
          answers without talking to a licensed clinician.
        </li>
        <li>
          Printable summaries are conversation aids for you and your doctor —
          they are not medical records.
        </li>
      </ul>

      <h2>Questions</h2>
      <p>Contact [CONTACT EMAIL] with questions about this disclaimer.</p>
    </>
  );
}
