// Medical Disclaimer — incorporated into the Terms of Use (section 2) and
// shown to every visitor via the consent banner. Its substance MUST stay
// aligned with the assistant's actual behavior in lib/systemPrompt.ts:
// single most-likely explanation, urgency classification, recovery/care
// plans, exercise programs with nutrition guidance, OTC-only medication
// information, and the healthcare-professional answer mode. If the system
// prompt gains a capability, disclose it here in the same release.
// Bracketed [PLACEHOLDERS] are company facts to fill in before launch.

import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Medical Disclaimer — Helagi",
  description:
    "What Helagi's health information is — and is not — and when you must see a real clinician instead.",
};

export default function MedicalDisclaimerPage() {
  return (
    <>
      <h1>Medical Disclaimer</h1>
      <p className="updated">Last updated: 23 July 2026 · Version 1.0</p>

      <h2>1. Helagi is not a doctor</h2>
      <p>
        Helagi provides general health information generated by an artificial
        intelligence system, grounded where possible in the World Health
        Organization&rsquo;s ICD-11 classification. Everything it tells you is{" "}
        <strong>informational only</strong>: it is not a medical diagnosis,
        not medical advice, not a treatment recommendation, and not a
        prescription. Using Helagi does not create a doctor&ndash;patient or
        any other professional-care relationship. Helagi does not replace a
        doctor, nurse, pharmacist, physiotherapist, mental-health
        professional, emergency service, or any other qualified healthcare
        provider — and it is not a medical device and has not been reviewed
        or approved by any health authority. Use of WHO ICD-11 terminology
        does not mean the WHO endorses Helagi or its answers.
      </p>

      <h2>2. In an emergency</h2>
      <p>
        If you have severe chest pain, trouble breathing, heavy bleeding,
        stroke symptoms (face drooping, arm weakness, speech difficulty),
        signs of a severe allergic reaction, a serious injury, thoughts of
        harming yourself, or any other situation that may be an emergency:{" "}
        <strong>
          call your local emergency number (such as 112 or 911) immediately
        </strong>
        . Do not wait for a chat response, and do not use Helagi to decide
        whether to call.
      </p>
      <p>
        If you are struggling with thoughts of suicide or self-harm, please
        reach out now to your local emergency number or a suicide-prevention
        helpline in your country — most countries have one that is free and
        available around the clock. Helagi is not a crisis service.
      </p>

      <h2>3. How Helagi answers — and why that can be wrong</h2>
      <ul>
        <li>
          <strong>One most-likely explanation.</strong> Helagi is designed to
          commit to the <em>single most likely</em> explanation for your
          symptoms rather than listing every possibility. That makes answers
          clearer — but it also means other, possibly more serious, causes
          exist that the answer does not mention. Only a clinician who can
          examine you, order tests, and see your full history can diagnose
          you.
        </li>
        <li>
          <strong>Urgency ratings are estimates.</strong> Helagi classifies
          situations (emergency, same-day care, doctor visit, self-care).
          These ratings are AI-generated estimates based only on what you
          typed. If your symptoms feel worse than the rating suggests, or are
          getting worse, or simply worry you — seek medical care regardless
          of what Helagi said.
        </li>
        <li>
          <strong>AI can be wrong while sounding confident.</strong> Answers
          can be inaccurate, incomplete, or out of date, may not reflect the
          latest research or your local medical guidelines, and are not
          personalized to your full medical history, medications, allergies,
          or test results.
        </li>
        <li>
          <strong>Helagi cannot see you.</strong> It has no access to your
          body, vital signs, laboratory results, imaging, or records — only
          your words.
        </li>
      </ul>

      <h2>4. Medication</h2>
      <p>
        Helagi may mention over-the-counter options as general information —
        always follow the package instructions and ask a pharmacist when
        unsure. It is designed never to instruct you on prescription
        medication or dosing.{" "}
        <strong>
          Never start, stop, or change any medication based on Helagi&rsquo;s
          answers without talking to a licensed clinician or pharmacist
        </strong>
        , and treat any answer that appears to instruct otherwise as an error
        on our side — do not follow it, and please report it to us.
      </p>

      <h2>5. Self-care plans, exercise programs, and nutrition guidance</h2>
      <p>
        Helagi can build recovery, care, and management plans, exercise
        programs, and general nutrition guidance. These are generic wellness
        suggestions, not a prescribed course of treatment, physiotherapy, or
        a clinical diet plan. Before following one:
      </p>
      <ul>
        <li>
          check with your doctor or physiotherapist first if you are
          pregnant, recovering from surgery or injury, or have a heart
          condition, chronic illness, or any other relevant medical
          condition;
        </li>
        <li>
          stop immediately and seek care if you experience chest pain,
          dizziness, severe shortness of breath, or sharp or worsening pain —
          never train &ldquo;through&rdquo; those signs;
        </li>
        <li>
          remember that a plan built from a short chat cannot account for
          everything about your body — progress conservatively.
        </li>
      </ul>
      <p>
        A &ldquo;see a doctor if&rdquo; trigger in a plan (for example,
        &ldquo;not improving after three days&rdquo;) is a minimum, not a
        maximum: see a doctor sooner whenever you are concerned.
      </p>

      <h2>6. For healthcare professionals</h2>
      <p>
        Helagi can present answers in a clinical format for healthcare
        professionals, including suggested assessments and management
        considerations. These are informational decision-support suggestions
        only: they do not replace your clinical judgment, examination,
        institutional protocols, or local guidelines, and they are not a
        consultation or second opinion. You remain fully and solely
        responsible for all clinical decisions and for verifying anything
        Helagi outputs before it influences patient care. Do not enter
        information that identifies a patient.
      </p>

      <h2>7. Documents Helagi produces</h2>
      <p>
        The &ldquo;Summary for your doctor&rdquo; / &ldquo;Make PDF&rdquo;
        feature turns a conversation into a printable document — a
        conversation aid to help you and your clinician talk, or a formatted
        plan. These documents are <strong>not medical records</strong>, not
        referral letters, and not certificates of any kind, and they may
        contain the same errors as the underlying conversation. Your
        clinician should treat them as your own account of your situation.
      </p>

      <h2>8. Your responsibility</h2>
      <p>
        You are responsible for how you use Helagi&rsquo;s information. See a
        qualified professional for any diagnosis or treatment decision;
        always seek care when symptoms are severe, persistent, or worsening —
        whatever Helagi said; and never disregard or delay professional
        medical advice because of something you read here. This disclaimer is
        incorporated into our{" "}
        <Link href="/legal/terms">Terms of Use</Link>, which you accept
        before using the service.
      </p>

      <h2>9. Questions and reporting concerns</h2>
      <p>
        If an answer seems medically wrong or unsafe, we genuinely want to
        know: contact [PRIVACY CONTACT EMAIL]. Questions about this
        disclaimer go to the same address.
      </p>
    </>
  );
}
